### ISSUE TITLE
The solution is not an OCT?

### ISSUE THREAD

**Issue by yanglin-jason** [TheoryInPractice/practical-oct#2]
Hello,

I have tried some solvers, including Akiba-Iwata, Heuristics, and Iterative Compression, on aa10 graph(located in data/sanitized/<file_format>/aa10). All of these solvers return a certificate set of {0, 1, 18, 21, 25, 32}. However, after removing these nodes from the original aa10 graph, the remaining graph is not a bipartite graph (tested with networkx.algorithm.bipartite.is_bipartite() function).

Did I miss some import steps?

****
$ python -m src.akiba_iwata.solver --convert-to-oct data/sanitized/snap/aa10.snap
0.2,6,"[0, 1, 18, 21, 25, 32]"

$ src/heuristics/heuristic_solver 1000*10 data/sanitized/edgelist/aa10.edgelist
6,31,"[0,1,18,21,25,32]"

$ python -m src.huffner.solver data/sanitized/huffner/aa10.huffner
0.0,6,"['0', '1', '18', '21', '25', '32']"
****

**Comment by EricHorton** [comment]
I suspect this is a simple issue with node labeling. If you copy/paste the Akiba/Iwata or heuristic solver output list into Python, it will be parsed as a list of ints. However, all of the graph nodes are labeled with strings. Networkx doesn't remove the correct nodes if you call `G.remove_nodes_from([0, 1, 18, 21, 25, 32])`, since, for example, `0 != '0'`.

Try the following and let us know if you have any issues.

```
$ python
>>> from pathlib import Path
>>> from networkx.algorithms.bipartite import is_bipartite
>>> import networkx as nx
>>>
>>> g = nx.parse_edgelist(Path('data/sanitized/edgelist/aa10.edgelist').read_text().split('\n')[1:])
>>> len(g.nodes)
69
>>> is_bipartite(g)
False
>>>
>>> # Node removal with integer labels. This should do nothing.
... g.remove_nodes_from([0, 1, 18, 21, 25, 32])
>>> len(g.nodes)
69
>>> is_bipartite(g)
False
>>>
>>> # Node removal with string labels. This should succeed.
... g.remove_nodes_from(['0', '1', '18', '21', '25', '32'])
>>> len(g.nodes)
63
>>> is_bipartite(g)
True
```

Our apologies for the confusion.

**Comment by yanglin-jason** [comment]
> I suspect this is a simple issue with node labeling. If you copy/paste the Akiba/Iwata or heuristic solver output list into Python, it will be parsed as a list of ints. However, all of the graph nodes are labeled with strings. Networkx doesn't remove the correct nodes if you call `G.remove_nodes_from([0, 1, 18, 21, 25, 32])`, since, for example, `0 != '0'`.
> 
> Try the following and let us know if you have any issues.
> 
> ```
> $ python
> >>> from pathlib import Path
> >>> from networkx.algorithms.bipartite import is_bipartite
> >>> import networkx as nx
> >>>
> >>> g = nx.parse_edgelist(Path('data/sanitized/edgelist/aa10.edgelist').read_text().split('\n')[1:])
> >>> len(g.nodes)
> 69
> >>> is_bipartite(g)
> False
> >>>
> >>> # Node removal with integer labels. This should do nothing.
> ... g.remove_nodes_from([0, 1, 18, 21, 25, 32])
> >>> len(g.nodes)
> 69
> >>> is_bipartite(g)
> False
> >>>
> >>> # Node removal with string labels. This should succeed.
> ... g.remove_nodes_from(['0', '1', '18', '21', '25', '32'])
> >>> len(g.nodes)
> 63
> >>> is_bipartite(g)
> True
> ```
> 
> Our apologies for the confusion.

Thanks for the answer.  Issue is closed
